name: Testing

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install packages
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Run integration tests
      run: npm run build && npm run test:integration

    - name: Run linting
      run: npm run lint
